name: Build BIOS DB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"
        ./build_db.py
        git add bios_db.json
        git commit -m "-" || true
        git push origin main